/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Arell
 */
public class Juego extends javax.swing.JFrame {
int x,y;
int level = 0;
        String lvl2 = "/multimedia/drive-download-20240419T015035Z-001/FondoLvl2.png";
        String sonic = "/multimedia/drive-download-20240419T015035Z-001/Sonic.png";
        String sonicD = "/multimedia/drive-download-20240419T015035Z-001/SonicDerecha.png";
        String sonicI = "/multimedia/drive-download-20240419T015035Z-001/SonicIzquierda.png";


        
        


    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
     //   this.setSize(490, 501);
        IMario.setFocusable(true);
        this.setTitle("Ing de Software [Sonic Proyect]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ICañon2 = new javax.swing.JLabel();
        ICañon3 = new javax.swing.JLabel();
        IMario = new javax.swing.JLabel();
        IFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ICañon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/drive-download-20240419T015035Z-001/Cañon.png"))); // NOI18N
        getContentPane().add(ICañon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 50, 40));

        ICañon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/drive-download-20240419T015035Z-001/Cañon.png"))); // NOI18N
        getContentPane().add(ICañon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 50, 40));

        IMario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/drive-download-20240419T015035Z-001/Sonic.png"))); // NOI18N
        IMario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IMarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IMarioKeyReleased(evt);
            }
        });
        getContentPane().add(IMario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 40, 60));

        IFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/drive-download-20240419T015035Z-001/FondoLvl1.png"))); // NOI18N
        getContentPane().add(IFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IMarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMarioKeyPressed
       //  TODO add your handling code here:
               // TODO add your handling code here:
        x = IMario.getX();
        y = IMario.getY();
        System.out.println(IMario.getLocation());
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_LEFT:
                IMario.setIcon(new ImageIcon(getClass().getResource(sonic)));
                IMario.setLocation(x-2,y);
                if (IMario.getX() <= 0) {
                    IMario.setLocation(10,y);
                }
                break;
            case KeyEvent.VK_RIGHT:
                IMario.setIcon(new ImageIcon(getClass().getResource(sonic)));
                IMario.setLocation(x+2,y);
                if (IMario.getX() == 500 && level == 0) {
                    IMario.setLocation(0,y);
                    IFondo.setIcon(new ImageIcon(getClass().getResource(lvl2)));
                }
                break;
            case KeyEvent.VK_UP:
                IMario.setIcon(new ImageIcon(getClass().getResource(sonic)));
                IMario.setLocation(x,y-2);
                if (IMario.getY() <= 144) {
                    IMario.setLocation(x,y);
                }
                break;   
            case KeyEvent.VK_DOWN:
                IMario.setIcon(new ImageIcon(getClass().getResource(sonic)));
                IMario.setLocation(x,y+2);
                if (IMario.getY() >= 150) {
                    IMario.setLocation(x,y);
                }
                break;
        } 
    }//GEN-LAST:event_IMarioKeyPressed

    private void IMarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMarioKeyReleased
        // TODO add your handling code here:
        IMario.setIcon(new ImageIcon(getClass().getResource(sonic)));
    }//GEN-LAST:event_IMarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICañon2;
    private javax.swing.JLabel ICañon3;
    private javax.swing.JLabel IFondo;
    private javax.swing.JLabel IMario;
    // End of variables declaration//GEN-END:variables
}
